import type {
  CampusVisit,
  School,
  Scholarship,
  StudentProfile,
} from "./types";

// Seeded demo profile. In production this comes from the student's Profile
// Passport (grade, career interest, budget, location, confidence, etc.).
export const profile: StudentProfile = {
  name: "Maya Rivera",
  grade: "senior",
  homeState: "TX",
  gpa: 3.8,
  sat: 1340,
  intendedMajor: "Computer Science",
  careerInterest: "Building software products",
  budget: 25_000,
  householdIncome: 55_000,
  householdSize: 4,
  firstGen: true,
  settingPreferences: ["urban", "suburban"],
  priorities: [
    "Strong CS program",
    "Research opportunities",
    "Affordable for my family",
    "Diverse community",
    "Internship pipeline",
  ],
};

// Schools the student has expressed interest in. Pricing reflects the student's
// in-state status (TX) where relevant — UT Austin and Texas A&M are in-state.
export const schools: School[] = [
  {
    id: "ut-austin",
    name: "University of Texas at Austin",
    city: "Austin",
    state: "TX",
    kind: "public",
    setting: "urban",
    size: 42_000,
    admitRate: 0.31,
    satRange: [1230, 1480],
    gradRate: 0.88,
    stickerPrice: 28_000,
    inState: true,
    medianEarnings: 75_000,
    netPriceByIncome: {
      band0_30k: 9_800,
      band30_48k: 11_200,
      band48_75k: 15_400,
      band75_110k: 19_800,
      band110kPlus: 24_500,
    },
    program: {
      major: "Computer Science",
      offered: true,
      strength: 92,
      medianEarnings: 108_000,
      careers: ["Software Engineer", "Product Manager", "ML Engineer"],
      highlight: "Top-10 CS department with a guaranteed-transfer research track.",
    },
    blurb: "Flagship public in a booming tech city, strong in-state value.",
  },
  {
    id: "texas-am",
    name: "Texas A&M University",
    city: "College Station",
    state: "TX",
    kind: "public",
    setting: "suburban",
    size: 57_000,
    admitRate: 0.63,
    satRange: [1160, 1390],
    gradRate: 0.84,
    stickerPrice: 27_000,
    inState: true,
    medianEarnings: 70_000,
    netPriceByIncome: {
      band0_30k: 8_400,
      band30_48k: 9_900,
      band48_75k: 13_600,
      band75_110k: 17_500,
      band110kPlus: 22_000,
    },
    program: {
      major: "Computer Science",
      offered: true,
      strength: 82,
      medianEarnings: 95_000,
      careers: ["Software Engineer", "Systems Engineer", "Data Engineer"],
      highlight: "Huge employer network and a strong co-op/internship pipeline.",
    },
    blurb: "Large, spirited campus with deep industry recruiting ties.",
  },
  {
    id: "georgia-tech",
    name: "Georgia Institute of Technology",
    city: "Atlanta",
    state: "GA",
    kind: "public",
    setting: "urban",
    size: 18_000,
    admitRate: 0.16,
    satRange: [1370, 1530],
    gradRate: 0.92,
    stickerPrice: 53_000,
    inState: false,
    medianEarnings: 86_000,
    netPriceByIncome: {
      band0_30k: 18_900,
      band30_48k: 21_400,
      band48_75k: 27_800,
      band75_110k: 34_200,
      band110kPlus: 41_500,
    },
    program: {
      major: "Computer Science",
      offered: true,
      strength: 95,
      medianEarnings: 122_000,
      careers: ["Software Engineer", "ML Engineer", "Robotics Engineer"],
      highlight: "Threads curriculum lets you specialize CS toward a career path.",
    },
    blurb: "Elite engineering school; out-of-state pricing is the catch.",
  },
  {
    id: "uc-berkeley",
    name: "UC Berkeley",
    city: "Berkeley",
    state: "CA",
    kind: "public",
    setting: "urban",
    size: 32_000,
    admitRate: 0.11,
    satRange: [1330, 1530],
    gradRate: 0.93,
    stickerPrice: 68_000,
    inState: false,
    medianEarnings: 88_000,
    netPriceByIncome: {
      band0_30k: 27_500,
      band30_48k: 29_900,
      band48_75k: 36_400,
      band75_110k: 44_800,
      band110kPlus: 58_000,
    },
    program: {
      major: "Computer Science",
      offered: true,
      strength: 96,
      medianEarnings: 134_000,
      careers: ["Software Engineer", "Research Scientist", "Founder"],
      highlight: "Pipeline straight into Bay Area startups and big tech.",
    },
    blurb: "World-class CS, but little aid for out-of-state families.",
  },
  {
    id: "rice",
    name: "Rice University",
    city: "Houston",
    state: "TX",
    kind: "private",
    setting: "urban",
    size: 4_500,
    admitRate: 0.08,
    satRange: [1490, 1560],
    gradRate: 0.94,
    stickerPrice: 75_000,
    inState: true,
    medianEarnings: 80_000,
    netPriceByIncome: {
      band0_30k: 4_200,
      band30_48k: 6_800,
      band48_75k: 12_500,
      band75_110k: 22_000,
      band110kPlus: 41_000,
    },
    program: {
      major: "Computer Science",
      offered: true,
      strength: 90,
      medianEarnings: 118_000,
      careers: ["Software Engineer", "Quant Developer", "Founder"],
      highlight: "Tiny classes; meets full demonstrated need with little loan.",
    },
    blurb: "Small private with generous need-based aid for families like yours.",
  },
  {
    id: "asu",
    name: "Arizona State University",
    city: "Tempe",
    state: "AZ",
    kind: "public",
    setting: "urban",
    size: 65_000,
    admitRate: 0.88,
    satRange: [1120, 1370],
    gradRate: 0.66,
    stickerPrice: 43_000,
    inState: false,
    medianEarnings: 62_000,
    netPriceByIncome: {
      band0_30k: 13_500,
      band30_48k: 15_200,
      band48_75k: 18_900,
      band75_110k: 23_400,
      band110kPlus: 29_000,
    },
    program: {
      major: "Computer Science",
      offered: true,
      strength: 74,
      medianEarnings: 88_000,
      careers: ["Software Engineer", "QA Engineer", "IT Analyst"],
      highlight: "Automatic merit scholarships make the OOS price competitive.",
    },
    blurb: "Accessible admit; merit aid is the lever that makes it affordable.",
  },
];

export const scholarships: Scholarship[] = [
  {
    id: "gates",
    name: "Gates Scholarship",
    sponsor: "Bill & Melinda Gates Foundation",
    amount: 40_000,
    renewable: true,
    deadline: "2026-09-15",
    eligibility: [
      "First-generation college student",
      "Pell-eligible / high financial need",
      "Minimum 3.3 GPA",
      "U.S. citizen or eligible non-citizen",
    ],
    match: { firstGenOnly: true, minGpa: 3.3 },
    effortHours: 8,
    status: "tracking",
    url: "https://www.thegatesscholarship.org",
  },
  {
    id: "coca-cola",
    name: "Coca-Cola Scholars Program",
    sponsor: "Coca-Cola Foundation",
    amount: 20_000,
    renewable: false,
    deadline: "2026-10-31",
    eligibility: [
      "High school senior",
      "Minimum 3.0 GPA",
      "Demonstrated leadership & service",
    ],
    match: { minGpa: 3.0 },
    effortHours: 4,
    status: "not_started",
    url: "https://www.coca-colascholarsfoundation.org",
  },
  {
    id: "swe",
    name: "Society of Women Engineers Scholarship",
    sponsor: "SWE",
    amount: 15_000,
    renewable: true,
    deadline: "2026-08-01",
    eligibility: [
      "Pursuing an ABET-accredited engineering/CS major",
      "Minimum 3.0 GPA",
    ],
    match: { majors: ["Computer Science", "Engineering"], minGpa: 3.0 },
    effortHours: 3,
    status: "not_started",
    url: "https://swe.org/scholarships",
  },
  {
    id: "terry",
    name: "Terry Foundation Scholarship",
    sponsor: "Terry Foundation",
    amount: 30_000,
    renewable: true,
    deadline: "2026-12-01",
    eligibility: [
      "Texas resident attending a partner Texas university",
      "Strong academics & financial need",
    ],
    match: { states: ["TX"] },
    effortHours: 5,
    status: "tracking",
    url: "https://www.terryfoundation.org",
  },
  {
    id: "generation-google",
    name: "Generation Google Scholarship",
    sponsor: "Google",
    amount: 10_000,
    renewable: false,
    deadline: "2026-12-04",
    eligibility: [
      "Intending to enroll in a CS or related degree",
      "Strong academic record",
      "Demonstrated leadership in the CS community",
    ],
    match: { majors: ["Computer Science"] },
    effortHours: 3,
    status: "in_progress",
    url: "https://buildyourfuture.withgoogle.com",
  },
  {
    id: "horatio-alger",
    name: "Horatio Alger National Scholarship",
    sponsor: "Horatio Alger Association",
    amount: 25_000,
    renewable: false,
    deadline: "2026-10-25",
    eligibility: [
      "Demonstrated financial need (under $55k household)",
      "Faced & overcome adversity",
      "Minimum 2.0 GPA",
    ],
    match: { minGpa: 2.0 },
    effortHours: 4,
    status: "not_started",
    url: "https://scholars.horatioalger.org",
  },
];

// Starter visit plans for a couple of schools; the rest start as fresh ideas.
export const initialVisits: CampusVisit[] = [
  {
    schoolId: "ut-austin",
    mode: "in_person",
    status: "planned",
    date: "2026-07-12",
    checklist: [
      { id: "tour", label: "Book official campus tour", done: true },
      { id: "cs-dept", label: "Email CS dept to sit in on a class", done: false },
      { id: "dorm", label: "See a freshman dorm", done: false },
      { id: "aid", label: "Stop by financial aid office", done: false },
    ],
  },
  {
    schoolId: "rice",
    mode: "virtual",
    status: "scheduled",
    date: "2026-06-28",
    checklist: [
      { id: "info-session", label: "Register for virtual info session", done: true },
      { id: "student-panel", label: "Join the student Q&A panel", done: false },
      { id: "aid", label: "Ask about need-based aid for first-gen", done: false },
    ],
  },
];

// Reusable visit checklist applied when a student starts planning a new visit.
export const defaultChecklist = [
  "Book official campus tour",
  "Sit in on a class in my major",
  "Talk to a current student",
  "See a freshman dorm & dining hall",
  "Visit the financial aid office",
  "Walk the surrounding neighborhood",
];

/** Profile-aware prompts the student can ask on a visit. */
export function visitPrompts(majorLabel: string): {
  category: string;
  questions: string[];
}[] {
  return [
    {
      category: "Academics & your major",
      questions: [
        `How easy is it to actually get into ${majorLabel} classes I need?`,
        "What does undergrad research look like for first-years?",
        "How big are intro classes, and who teaches them?",
      ],
    },
    {
      category: "Money & aid",
      questions: [
        "What did your aid package actually cover vs. the sticker price?",
        "Are there paid research or work-study jobs on campus?",
        "How common are scholarships that renew all four years?",
      ],
    },
    {
      category: "Belonging & support",
      questions: [
        "Where do first-gen students find their people here?",
        "What support exists if a class isn't going well?",
        "Do you feel like you belong here? Why or why not?",
      ],
    },
    {
      category: "Career outcomes",
      questions: [
        "How did you find your first internship?",
        "Which companies recruit on campus for my field?",
        "What do recent grads in my major end up doing?",
      ],
    },
  ];
}
